#app:
app:
  version: '@project.version@ c:@git.commit.id.abbrev@_@git.build.time@ b:@maven.build.timestamp@'
  cors-allowed-origins: [ "*" ]
  first-admin:
    username: # REQUIRED first admin username
    name: # REQUIRED first admin name
    password: # REQUIRED first admin password
jwt:
  max-refresh-tokens-per-user: 5
  secret: fill-me-later
  access-duration: PT5M
  refresh-duration: P90D
spring:
  jmx:
    default-domain: com.a6raywa1cher.hackservspring
    unique-names: true
spring.jackson.mapper.DEFAULT_VIEW_INCLUSION: true
spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: # REQUIRED database jdbc url
spring.datasource.username: # REQUIRED database username
spring.datasource.password: # REQUIRED database password
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.dialect: com.a6raywa1cher.hackservspring.utils.hibernate.PostgreSqlDialectFixed
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
